services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: service-manager-dev
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:15
    container_name: service-manager-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_manager
    ports:
      - "5432:5432"
    volumes:
      #setting untuk membuat data tetap utuh walaupun container di drop/restart
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: service-manager-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
