# Gunakan Node.js versi terbaru
FROM node:20-alpine

# Tentukan workdir di dalam container
WORKDIR /app

# Salin package.json dan package-lock.json untuk instalasi dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Salin seluruh kode sumber ke dalam container
COPY . .

# Install nodemon secara global
RUN npm install -g nodemon

# Expose port untuk akses aplikasi
EXPOSE 3001

# Jalankan aplikasi dengan nodemon agar auto-restart saat file berubah
CMD ["npm", "run", "dev"]
